### ISSUE TITLE
To accomplish your code in swift

### ISSUE THREAD

**Issue by nataliemichael** [samwize/UINavigationBar-Addition#3]
Hey! I based some swift code off of your code, so here it is :)

import Foundation
import UIKit

extension UINavigationBar {
	
	func hideBottomHairline() {
		var imageView: UIImageView? = findHairlineImageViewunder(self)
		if imageView {
			imageView!.hidden = true
		}
	}
	
	func showBottomHairline() {
		var imageView: UIImageView? = findHairlineImageViewunder(self)
		if imageView {
			imageView!.hidden = false
		}
	}
	
	func findHairlineImageViewunder(view: UIView) -> UIImageView? {
		if (view is UIImageView) && (1.0 >= view.bounds.size.height) {
			return view as? UIImageView
		}
		for subView: AnyObject in view.subviews {
			var imageView: UIImageView? = findHairlineImageViewunder(subView as UIView)
			if imageView {
				return imageView
			}
		}
		return nil
	}
}

**Comment by Isuru-Nanayakkara** [comment]
+1

**Comment by samwize** [comment]
Thanks. But not necessary to port to Swift.
