### ISSUE TITLE
MakeTransparent method not available in latest pod install

### ISSUE THREAD

**Issue by amna-malik** [samwize/UINavigationBar-Addition#4]
If I install your library using pod "UINavigationBar+Addition", it doesn't bring in makeTransparent method in cloned code. probably you need to update code version in  your podspec file so it can refer to latest changes.

**Comment by migue1s** [comment]
As a workaround until the original author updates the podspec, you can use

```
pod 'UINavigationBar+Addition', git: 'https://github.com/samwize/UINavigationBar-Addition', :tag => '1.2.0'
```
This will install the latest version to your project (1.2.0).

**Comment by RyanCopley** [comment]
@samwize please help :(

**Comment by samwize** [comment]
@RyanCopley I forgot to tag the version 1.2.0, but this was fixed a few months ago. Is it still not correct?

**Comment by migue1s** [comment]
@samwize It's still not correct. Although it has been tagged 1.2.0, cocoapods only recognises version 1.0.0 for some reason. Since the "pod badge" in the repo says invalid, maybe the podspec has an error? Have you tried running "pod lib lint" to check if everything's alright?

**Comment by samwize** [comment]
@migue1s Thanks. Indeed something is not right.. The podspec description is shorter than summary, and that's not ok. It's now fixed.
